### ISSUE TITLE
some video link failure

### ISSUE THREAD

**Issue by pandalee99** [chenzomi12/AISystem#120]
https://chenzomi12.github.io/061FW_AICluster/01.introduction.html

<img width="709" alt="image" src="https://github.com/chenzomi12/AISystem/assets/46820719/45be1405-d7e6-4408-9243-5d21435e5045">

**Comment by chenzomi12** [comment]
网页版本暂时都对不上了，内容经过了整体结构调整，可以重点留意 https://github.com/chenzomi12/AISystem/ 里面的内容更新。
