### ISSUE TITLE
Incorrect Bandwidth Units in NVLink 1.0 image for P100

### ISSUE THREAD

**Issue by wan-nan** [chenzomi12/AISystem#271]
Path of the image: `02Hardware/04NVIDIA/images/05DeepNvlink07.png`

The image depicting NVLink 1.0 for the P100 shows the bandwidth as "20 **Gbps**" per link. This is incorrect and should be "20 **GBps**" (Gigabytes per second) per link.
Additionally, the total unidirectional bandwidth is listed as "80 Gbps" and the bidirectional bandwidth as "160 Gbps," which should be "80 GBps" and "160 GBps," respectively.
The image is referenced in `02Hardware/04NVIDIA/05DeepNvlink.md`

![image](https://github.com/chenzomi12/AISystem/assets/54490797/454c97c7-2c0e-4f0e-a2cd-a6132bcba949)

**Comment by chenzomi12** [comment]
Thanks， i will rewrite the image.
