### ISSUE TITLE
如何理解: 即使在 DSA 上为 SIMD 硬件封装了 SIMT 前端，如果遇到执行指令有依赖，基础性能也会非常差

### ISSUE THREAD

**Issue by Orca-bit** [chenzomi12/AISystem#277]
GPU也是SIMT前端+SIMD后端，是如何解决这个问题的，通过CUDA吗

**Comment by chenzomi12** [comment]
我的理解是：线程硬件化，dispatch 到 SIMD的多计算核pipeline 上。DSA 的 NPU 目前并没有按照这种方式去做，核数有限，把计算核心做大加 SIMT 前端，不是解决问题的本质。
