### ISSUE TITLE
请问B站deepspeed系列视频对应的PPT在哪个位置？

### ISSUE THREAD

**Issue by lemon-little** [chenzomi12/AISystem#281]

**Comment by TBAALi** [comment]
【自动回复】你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。Thank you for your email. Unfortunately, I am currently out of the office. During this period of time, I will have limited access to my email.

**Comment by chenzomi12** [comment]
https://github.com/chenzomi12/AIFoundation/， 在这个地址哈

**Comment by Verat42z9sgL9s89xemos** [comment]
PPT打不开了

**Comment by chenzomi12** [comment]
可以直接下载
