### ISSUE TITLE
README中YouTube链接404

### ISSUE THREAD

**Issue by WHFF521** [chenzomi12/AISystem#291]
README开头视频托管链接中油管链接404，
<img width="1552" alt="Screenshot 2024-11-25 at 17 09 00" src="https://github.com/user-attachments/assets/36e13243-417b-4e33-93ec-44dc7ad0f71b">

我自己根据B站up姓名搜了一下，油管的链接应该是[https://www.youtube.com/@ZOMI666/videos](https://www.youtube.com/@ZOMI666/videos)吧。

**Comment by chenzomi12** [comment]
对的，感谢！
