### ISSUE TITLE
关于混合精度训练中的loss scaling

### ISSUE THREAD

**Issue by wln20** [chenzomi12/AISystem#295]
zomi您好！非常感谢您精心准备的内容，受益良多。有个小问题：
在Tensor Core基本原理这一节讲义中，提到了混合精度训练技术，但其中并没有提到loss scaling（或者说gradient scaling）。按我的理解，如果没有scaling/unscaling过程的话那么fp16和fp32之间的转换似乎就没有意义了？不知道我的理解是否正确，如果可以的话我可以加上这一小部分的内容，感觉这样会更容易理解混合精度设计的意义。谢谢！

**Comment by chenzomi12** [comment]
可以的，欢迎你提交 PR 过来仓！感谢！
